apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceguards.ops.example.com
spec:
  group: ops.example.com
  scope: Namespaced
  names:
    kind: ServiceGuard
    plural: serviceguards
    singular: serviceguard
    shortNames: ["sg"]
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["targetDeployment"]
              properties:
                targetDeployment: { type: string }
                minReplicas: { type: integer, minimum: 1, default: 2 }
                maxReplicas: { type: integer, minimum: 1, default: 6 }
                cpuHighPercent: { type: integer, minimum: 1, maximum: 100, default: 80 }
                cpuLowPercent: { type: integer, minimum: 0, maximum: 100, default: 20 }
                restartOnCrashLoop: { type: boolean, default: true }
                prometheusUrl:
                  type: string
                  default: "http://prometheus-server.monitoring.svc.cluster.local"
                mode:
                  type: string
                  enum: ["heal", "advise"]
                  default: "heal"
                gcDeadPods: { type: boolean, default: true }
                deadPodTTLMinutes: { type: integer, minimum: 1, default: 60 }
                oomRestartEnabled: { type: boolean, default: true }
                oomRestartBudget: { type: integer, minimum: 1, default: 3 }
                oomWindowMinutes: { type: integer, minimum: 1, default: 30 }
                stuckTerminatingDetect: { type: boolean, default: true }
                stuckTerminatingGraceMinutes: { type: integer, minimum: 1, default: 15 }
                forceDeleteStuckPods: { type: boolean, default: false }
                forceDeleteOnlyIfNodeGone: { type: boolean, default: true }
                advisoryEnabled: { type: boolean, default: true }
                scheduleScaleDown: { type: boolean, default: false }
                quietReplicas: { type: integer, minimum: 1, default: 1 }
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Target
          type: string
          jsonPath: .spec.targetDeployment
        - name: Mode
          type: string
          jsonPath: .spec.mode
        - name: Replicas
          type: integer
          jsonPath: .status.currentReplicas
        - name: CPU%
          type: string
          jsonPath: .status.cpuPercent
        - name: Advisories
          type: integer
          jsonPath: .status.advisoryCount
